[package]
name = "imageproc"
version = "0.1.0"
authors = ["Rudolph Jacobs <rjacobs@retrorabbit.co.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
old = []

[dependencies]
clap = "2.33.0"
image = "0.22.3"
